### ISSUE TITLE
Bad performance of `fusedContextStageAttentionKernel`

### ISSUE THREAD

**Issue by Fonsifa** [LLMServe/SwiftTransformer#2]
![image](https://github.com/user-attachments/assets/960b0b41-95a7-447c-9155-cbb9396f90f4)
it seems  `fusedContextStageAttentionKernel`  is far inferior to the xformer’s performance.  I don't know if it's a problem with the kernel itself.

**Comment by interestingLSY** [comment]
Yes it's a problem with the kernel itself. As shown [here](https://github.com/LLMServe/SwiftTransformer/blob/7a386f3dde44f56b72e7485d633e9b350fdbdeb8/src/csrc/layer/attention.cc#L179), we use XFormer's kernel whenever possible.
