### ISSUE TITLE
what is the difference with FasterTransformer

### ISSUE THREAD

**Issue by seeyourcell** [LLMServe/SwiftTransformer#3]
what is the difference with FasterTransformer

**Comment by interestingLSY** [comment]
They are different projects for different purposes. FasterTransformer focuses on a wide range of models and architectures (somehow like an all-in-one right-out-of-the-box solution), while SwiftTransformer is mainly for research purpose (so it contains less code and only focuses on two or three models).

To be honest, both projects seem to be a little old. For example, both of them do not have FlashDecoding.
